package com.sample

import com.sample.Order;

rule Rule1_1
  when
    $o : Order(discount == 0)
  then
    System.out.println(kcontext.getRule().getName() + " is fired");
    // do something
end

rule Rule1_2
  when
    $o : Order(discount > 100)
  then
    System.out.println(kcontext.getRule().getName() + " is fired");
    // do something
end

rule Rule2_1
  when
    $o : Order(price >= 5000, price < 8000)
  then
    System.out.println(kcontext.getRule().getName() + " is fired");
    // do something
end

rule Rule2_2
  when
    $o : Order(price >= 8000)
  then
    System.out.println(kcontext.getRule().getName() + " is fired");
    // do something
end

rule Rule3_1
  when
    $o : Order(price >= 5000)
  then
    System.out.println(kcontext.getRule().getName() + " is fired");
    // do something
    $o.setDiscount($o.getDiscount() + 400);
    update($o);
end

rule Rule3_2
  when
    $o : Order(discount > 200)
  then
    System.out.println(kcontext.getRule().getName() + " is fired");
    // do something
end